const fs = require('fs');
const path = require('path');

// VERY SIMPLE markdown to HTML converter for the specific HarshGuruJi format
function markdownToHTML(markdown) {
    let html = markdown;
    
    // Convert Headers
    html = html.replace(/^### (.*$)/gim, '<h3>$1</h3>');
    html = html.replace(/^## (.*$)/gim, '<h2>$1</h2>');
    html = html.replace(/^# (.*$)/gim, '<h1>$1</h1>');
    
    // Convert Bold & Italics
    html = html.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
    html = html.replace(/\*(.*?)\*/g, '<em>$1</em>');
    
    // Convert Tables (Simple)
    html = html.replace(/\|(.+)\|/g, function(match, content) {
        if (content.includes('---')) return ''; // Skip separator
        const cells = content.split('|').map(c => `<td>${c.trim()}</td>`).join('');
        return `<tr>${cells}</tr>`;
    });
    // Wrap adjacent trs in table
    html = html.replace(/(<tr>.*?<\/tr>\n?)+/g, '<table class="ncert-table">$&</table>');
    html = html.replace(/<td>\*\*(.*?)\*\*<\/td>/g, '<th>$1</th>'); // Hack for table headers
    
    // Checkboxes
    html = html.replace(/- \[ \] (.*)/g, '<div class="checkbox">◻ $1</div>');
    html = html.replace(/- \[x\] (.*)/g, '<div class="checkbox">✅ $1</div>');

    // Bullet Points
    html = html.replace(/^- (.*$)/gim, '<li>$1</li>');
    html = html.replace(/(<li>.*<\/li>\n?)+/g, '<ul>$&</ul>');

    // Horizontal Rules
    html = html.replace(/^---$/gim, '<hr>');

    // Paragraphs
    html = html.split('\n').map(line => {
        if (line.trim() === '' || line.startsWith('<') || line.startsWith('⚠️') || line.startsWith('✅')) {
            return line;
        }
        return `<p>${line}</p>`;
    }).join('\n');

    return html;
}

const cssTemplate = `
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
    
    body {
        font-family: 'Inter', sans-serif;
        color: #333;
        line-height: 1.6;
        margin: 0;
        padding: 0;
        background: #f9fafb;
    }
    
    .page {
        background: white;
        width: 210mm;
        min-height: 297mm;
        margin: 20px auto;
        padding: 25mm 20mm;
        box-shadow: 0 0 10px rgba(0,0,0,0.1);
        box-sizing: border-box;
        position: relative;
    }
    
    h1 { color: #2563eb; font-size: 28px; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }
    h2 { color: #1e40af; font-size: 22px; margin-top: 30px; border-bottom: 1px solid #e5e7eb; padding-bottom: 5px; }
    h3 { color: #3b82f6; font-size: 18px; margin-top: 20px; }
    
    p { margin-bottom: 15px; }
    
    .ncert-table {
        width: 100%;
        border-collapse: collapse;
        margin: 20px 0;
    }
    .ncert-table th, .ncert-table td {
        border: 1px solid #d1d5db;
        padding: 12px;
        text-align: left;
    }
    .ncert-table th { background-color: #f3f4f6; }
    
    hr { border: 0; border-top: 1px dashed #cbd5e1; margin: 30px 0; }
    
    .footer {
        position: absolute;
        bottom: 15mm;
        left: 20mm;
        right: 20mm;
        border-top: 1px solid #e5e7eb;
        padding-top: 10px;
        font-size: 12px;
        color: #6b7280;
        display: flex;
        justify-content: space-between;
    }
    
    /* PRINT STYLES - This makes it output perfectly as a PDF when you hit Ctrl+P in Chrome */
    @media print {
        body { background: white; }
        .page { margin: 0; box-shadow: none; width: auto; height: auto; min-height: auto; padding: 0; }
        @page { size: A4; margin: 20mm; }
        .footer { position: fixed; bottom: 0; }
    }
</style>
`;

function generateHTML(inputFile, outputFile) {
    console.log("Reading Markdown from: " + inputFile);
    const mdContent = fs.readFileSync(inputFile, 'utf-8');
    
    const htmlBody = markdownToHTML(mdContent);
    
    const finalHTML = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>NCERT PDF Document</title>
        ${cssTemplate}
    </head>
    <body>
        <div class="page">
            ${htmlBody}
            
            <div class="footer">
                <span>HarshGuruJi Learning Hub | NCERT Aligned Resource</span>
                <span>Generated by System</span>
            </div>
        </div>
        <script>
            // Auto-trigger print dialog for saving to PDF
            // window.onload = () => window.print();
        </script>
    </body>
    </html>
    `;
    
    fs.writeFileSync(outputFile, finalHTML, 'utf-8');
    console.log("Successfully generated print-ready HTML: " + outputFile);
    console.log("-> Open this HTML file in Chrome and press Ctrl+P to save as a perfectly styled A4 PDF!");
}

// Example Execution
const inputPath = path.join(__dirname, '../learning/class-10/science/ncert/01-chemical-reactions-and-equations.md');
const outputPath = path.join(__dirname, '../learning/class-10/science/ncert/01-chemical-reactions-and-equations.html');

generateHTML(inputPath, outputPath);
